### ISSUE TITLE
It just doesn't work

### ISSUE THREAD

**Issue by carloshenriquecarniatto** [DevExpress/dashboard-extensions#10]
I tried to integrate the extension with my project but every time I register the extension it returns me the error devextreme-extension.js: 90 Uncaught TypeError: Cannot read property 'Dashboard' of undefined
     at webpackUniversalModuleDefinition (dfunnel-d3-item: 90)
     at devextreme-extensionao.js: 93 and don't add the extension I would like to know what is missing to work.

**Comment by SergeyNakhankov** [comment]
Hello,
Please submit a ticket to our DevExpress Support Center at http://devexpress.com/ask and describe the issue in greater detail. For better results, post your code so we can review it and determine what causes the issue.
