### ISSUE TITLE
Export Type Definitions

### ISSUE THREAD

**Issue by Mischala** [DevExpress/dashboard-extensions#11]
Trying to use these dashboard extensions in Typescript produces the following error
`Could not find a declaration file for module 'dashboard-extensions/dist/simple-table-item'.`

The Extensions are written in Typescript, could dwe not export them for typescript users?

Thanks

**Comment by SergeyNakhankov** [comment]
Hello,
I apologize for the delayed response. Currently, we do not provide TypeScript definition files for our sample dashboard extensions. I have passed your request to our R&D team so they can take it into account during future development. 

For now, you can write corresponding d.ts files manually and create a pull request so we can include your d.ts files in the dashboard-extensions repository.

If you face any issues with writing d.ts files, please raise a ticket to our DevExpress Support Center, our official technical support channel, at https://supportcenter.devexpress.com/.
