### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by NCelikok** [DevExpress/dashboard-extensions#15]
Hello,
I configured my application to use this extension. But when I clicked Mobile button nothing displays and when I traced I found an error in dashboard-panel.js/line 165
devices_1["default"].on("orientationChanged", 
function(e) {_this._actualPanelWidth($(window).width());})

Because  devices_1["default"] is undefined.

Thanks for your further help.

**Comment by dimarudnev** [comment]
Hi,

I reviewed the code of the Dashboard Panel Extension and found that the code related to devices_1["default"] was removed during refactoring (see the corresponding commit [https://github.com/DevExpress/dashboard-extensions/commit/6f4b0fa14cc002f6ffabcc8f33e82e30cca602ae](https://github.com/DevExpress/dashboard-extensions/commit/6f4b0fa14cc002f6ffabcc8f33e82e30cca602ae)). Please update to the latest version and check if the exception occurs. If it does not help, please create a small runnable project illustrating this issue. Also you can post your questions in our Support Center: [https://supportcenter.devexpress.com/ticket/list](https://supportcenter.devexpress.com/ticket/list).
