### ISSUE TITLE
funnel-3D-item Cannot read property 'removeChild' of null

### ISSUE THREAD

**Issue by Luan-Sens** [DevExpress/dashboard-extensions#16]
Funel 3D Item TypeError exception "Cannot read property 'removeChild' of null"
This happen when interract with filter component and the filter component have option "type" equals "Marked" and your value is null.

**Steps to reproduce:**
1. Create Dasboard with Funnel 3D Item and filter component like combo box.
2. Bind value and argument to Funnel Item.
3. Bind value to combo box filter.
4. Set combo box option in "Options" section("wrench icon") "Type" to "Marked".
5. Remove Tag "All" in combox for defining your value null.
6. Select any value in combo box.

Look Funnel component freeze in refresh and exception is throwed (see console).

This exception happen in line 211 on file funnel-d3-item.js
In call function removeChild from property parentNode when is undefined.

![work](https://user-images.githubusercontent.com/28359702/80725889-0df6c080-8ada-11ea-8e9e-2a0d0e69eaff.jpg)
![optionWrench](https://user-images.githubusercontent.com/28359702/80725968-2b2b8f00-8ada-11ea-8d0f-f1a028713e0f.jpg)
![empty-filter](https://user-images.githubusercontent.com/28359702/80725413-6a0d1500-8ad9-11ea-9ba7-ee94ca95285d.jpg)
![freeze](https://user-images.githubusercontent.com/28359702/80725428-6ed1c900-8ad9-11ea-9891-66f9c70b08ae.jpg)
![console](https://user-images.githubusercontent.com/28359702/80725438-71ccb980-8ad9-11ea-875a-a879a906ad43.jpg)
![code](https://user-images.githubusercontent.com/28359702/80725444-742f1380-8ad9-11ea-93db-2795b372bf7d.jpg)

**Comment by dimarudnev** [comment]
Hi,

I reproduced this behavior and created a separate ticket in our Support Center:
https://supportcenter.devexpress.com/ticket/details/t887089/web-dashboard-cannot-read-property-removechild-of-null-exception-when-filtering-a-custom
