### ISSUE TITLE
Error is thrown when resgisterExtension method is used on dashboard control

### ISSUE THREAD

**Issue by ninopetrovic** [DevExpress/dashboard-extensions#19]
Hello.

Since yesterday or maybe 2 days an fatal error is thrown when calling registerExtension method on our dashboard control.
![image](https://user-images.githubusercontent.com/43232121/81795691-ad6d7780-950c-11ea-9c2b-50c569875a8f.png)

We are on Angular 8  and devexpress dashboard versions (image bellow):
![image](https://user-images.githubusercontent.com/43232121/81795852-e73e7e00-950c-11ea-9821-7708fbb8239b.png)

Regards.

**Comment by sergey-kanaev** [comment]
Hello,

We have updated the master branch of our repository to use the latest Dashboard control enhancements (https://www.devexpress.com/subscriptions/new-2020-1.xml#dashboard). So the master branch is now incompatible with versions 19.1.* and 19.2.* of the Dashboard control.

The previous version of the Dashboard Extensions was moved to the branch named 2.0.0. If you want to use it with v19.1.6 of the Dashboard control, you need to update the package.json file by adding the branch name like this:

"dependencies": {
	"dashboard-extensions": "git+https://git@github.com/DevExpress/dashboard-extensions.git#2.0.0"
}
