### ISSUE TITLE
Mobile Version

### ISSUE THREAD

**Issue by NCelikok** [DevExpress/dashboard-extensions#20]
Hello,
I am using devexpress 19.2.7 version. I copied newest versions of dashboardpanel.html, dashboard-panel.css, dashboard-panel.js files into my project. When I clicked Mobile version panel stays at the same position as you can see from the screenshot. How can I fix these? Thanks a lot.

![Screen](https://user-images.githubusercontent.com/37617104/82530589-525c0600-9b46-11ea-8086-7cce418373b1.PNG)

**Comment by dimarudnev** [comment]
Hi, as I can see, this issue does not directly relate to the dashboard-panel, but to the fact that the Dashboard control did not switch to mobile mode. Please ensure that [mobile mode is enabled](https://docs.devexpress.com/Dashboard/119662/designer-and-viewer-applications/web-dashboard/mobile-layout#mobile-layouts-mode) and your [device is detected as mobile](https://docs.devexpress.com/Dashboard/js-DevExpress.Dashboard.MobileLayoutExtension#js_devexpress_dashboard_mobilelayoutextension_mobilelayoutenabled).
If it does not help, please create a small runnable project illustrating the issue and post it in our [Support Center](https://supportcenter.devexpress.com/ticket/list)

**Comment by NCelikok** [comment]
Thank you very much. When  I set "Always" for the MobileLayoutEnabled propery of the dashboard control. It worked fine.
