### ISSUE TITLE
Dashboard List Title

### ISSUE THREAD

**Issue by NCelikok** [DevExpress/dashboard-extensions#21]
Hello,

I want to change DASHBOARDS text on the panel. How can I do that?

![Screen](https://user-images.githubusercontent.com/37617104/82541238-cef7e000-9b58-11ea-8bbc-30d00c4e9813.PNG)

**Comment by Stason4eg** [comment]
Hello,

I apologize for the delayed response. If you need to change the "Dashboards" text, you can change the following line of code - https://github.com/DevExpress/dashboard-extensions/blob/82faedaadd154b39f04a0637432d26d58e9508dd/dist/dashboard-panel.html#L26
