### ISSUE TITLE
Online-map Marker clustering

### ISSUE THREAD

**Issue by Volume999** [DevExpress/dashboard-extensions#22]
Is it possible to add Marker Clustering to the online-map extension? I do not know how to change the layer and where it is defined...

**Comment by dimarudnev** [comment]
Hi,
We discussed a similar inquiry in the following ticket: [T569037](https://supportcenter.devexpress.com/ticket/details/t569037/how-to-enable-clustering-in-google-and-bing-map-extension). Please review it to learn how to enable clustering in the dxMap widget.
If this information does not help, please submit a separate ticket to our Support Center at [https://supportcenter.devexpress.com](https://supportcenter.devexpress.com/). We will be happy to help you.
