### ISSUE TITLE
Custom Dashboard List (Tree List) 

### ISSUE THREAD

**Issue by mtarabba** [DevExpress/dashboard-extensions#23]
Greetings 

I'm  trying to create a custom Tree List Menu in ASP.net to switch between dashboard, I got some tips that it can be work with JS, but looking at code I'm at lost where to start.
![image_2021-04-09_152144](https://user-images.githubusercontent.com/63328495/114143924-53a54580-9947-11eb-9d3e-5014237defb5.png)

**Comment by Stason4eg** [comment]
Hello,

It seems that you asked the same question in our Support Center - 
[t988495](https://supportcenter.devexpress.com/ticket/details/t988495/dashboard-for-web-form-use-tree-view-in-dashboard-panel). Let's continue our discussion there.
