### ISSUE TITLE
Can these extensions be used in the dashboard module of XAF?

### ISSUE THREAD

**Issue by tylike** [DevExpress/dashboard-extensions#9]
Can these extensions be used in the dashboard module of XAF?

**Comment by tylike** [comment]
![1](https://user-images.githubusercontent.com/920370/60970382-6ba3fb80-a354-11e9-96bf-8e1c7eed8dcd.png)
![2](https://user-images.githubusercontent.com/920370/60970389-72327300-a354-11e9-893a-c0a2e567124c.png)
![3](https://user-images.githubusercontent.com/920370/60970395-75c5fa00-a354-11e9-9282-24f8d91d9588.png)
![4](https://user-images.githubusercontent.com/920370/60970397-78285400-a354-11e9-85a9-f5f463ef8536.png)
If this supports xaf, what should I do?
thanks!

**Comment by tylike** [comment]
I created a new aspx interface. The script reference file must be placed after the < ASPX Dashboard > control tag.

This was tried in XAF:

`using DevExpress.DashboardWeb.Native;

public partial class Default : BaseXafPage {
    ...
    protected override void OnInit(EventArgs e) {
        base.OnInit(e);
        new WebFormsResourcesRegistrator().RegisterScripts(this);
    }
}`


But it didn't succeed.

**Comment by AndreyKozhevnikov** [comment]
Hello,
 
I answered you in the [T757337 - How to show a custom extension in a dashboard in an XAF application](https://isc.devexpress.com/Thread/WorkplaceDetails/T757337) thread. Please let's continue our discussion there.
 
Thanks,
Andrey
